services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: medical_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/medical_db
    volumes:
      - ./app:/code/app

volumes:
  postgres_data:
